export const SCHEMA_VERSION = "qm-monitor-v1";
export const TIMEZONE = "America/New_York";
export const DISPLAY_WEEK_LIMIT = 5;
export const STALE_AFTER_SECONDS = 6 * 60 * 60;
export const FETCH_TIMEOUT_MS = 4000;
export const LIVE_INGEST_BUDGET_MS = 20000;
export const SOURCE_CONCURRENCY = 6;
export const MAX_ITEMS_PER_SOURCE = 25;
export const CACHE_CONTROL = "no-store, no-cache, max-age=0, must-revalidate";

export const FETCH_HEADERS = {
  "User-Agent": "RegIntel-monitor/1.1 (Quality Manager regulatory monitoring)",
  Accept: "application/rss+xml, application/xml, text/xml, application/json, */*",
};

const FR_JSON = "https://www.federalregister.gov/api/v1/documents.json";
const FR_HHS = "conditions%5Bagencies%5D%5B%5D=health-and-human-services-department";
const FR_TYPES = "conditions%5Btype%5D%5B%5D=RULE&conditions%5Btype%5D%5B%5D=PRORULE";

export const MONITOR_FEEDS = [
  {
    id: "fr-snf-pps",
    folder: "official",
    title: "Federal Register - HHS/CMS - SNF PPS rules",
    queryLabel: "HHS/CMS · term SNF PPS · proposed/final rules",
    agency: "HHS / CMS",
    kind: "fr-api",
    url: `${FR_JSON}?${FR_HHS}&conditions%5Bterm%5D=SNF%20PPS&${FR_TYPES}&per_page=20&order=newest`,
  },
  {
    id: "fr-snf",
    folder: "official",
    title: "Federal Register - HHS/CMS - SNF rules",
    queryLabel: "HHS/CMS · term skilled nursing facility · proposed/final rules",
    agency: "HHS / CMS",
    kind: "fr-api",
    url: `${FR_JSON}?${FR_HHS}&conditions%5Bterm%5D=skilled%20nursing%20facility&${FR_TYPES}&per_page=20&order=newest`,
  },
  {
    id: "govinfo-fr-snf",
    folder: "official",
    title: "GovInfo FR - skilled nursing facility",
    queryLabel: 'Federal Register collection · "skilled nursing" OR "nursing facility" OR "skilled nursing facility"',
    agency: "Federal Register / GovInfo",
    kind: "govinfo-search",
    query: 'collection:(FR) ("skilled nursing" OR "nursing facility" OR "skilled nursing facility")',
  },
  {
    id: "govinfo-fr-nh",
    folder: "official",
    title: "GovInfo FR - nursing home",
    queryLabel: 'Federal Register collection · "nursing homes"',
    agency: "Federal Register / GovInfo",
    kind: "govinfo-search",
    query: 'collection:(FR) ("nursing homes" OR "nursing home")',
  },
  {
    id: "govinfo-fr-483",
    folder: "official",
    title: "GovInfo FR - 42 CFR 483",
    queryLabel: 'Federal Register collection · "42 CFR 483"',
    agency: "Federal Register / GovInfo",
    kind: "govinfo-search",
    query: 'collection:(FR) "42 CFR 483"',
  },
  {
    id: "govinfo-fr-ltc",
    folder: "official",
    title: "GovInfo FR - long-term care facility",
    queryLabel: 'Federal Register collection · "long-term care facility"',
    agency: "Federal Register / GovInfo",
    kind: "govinfo-search",
    query: 'collection:(FR) "long-term care facility"',
  },
  {
    id: "govinfo-fr-pps",
    folder: "official",
    title: "GovInfo FR - SNF PPS",
    queryLabel: 'Federal Register collection · "SNF PPS" OR "skilled nursing facility" PPS',
    agency: "Federal Register / GovInfo",
    kind: "govinfo-search",
    query: 'collection:(FR) ("SNF PPS" OR ("skilled nursing facility" AND PPS))',
  },
  {
    id: "govinfo-fr-qrp",
    folder: "official",
    title: "GovInfo FR - quality reporting nursing home",
    queryLabel: 'Federal Register collection · quality reporting AND (nursing home OR SNF)',
    agency: "Federal Register / GovInfo",
    kind: "govinfo-search",
    query: 'collection:(FR) "quality reporting" ("nursing home" OR SNF OR "skilled nursing")',
  },
  {
    id: "snn",
    folder: "context",
    title: "Skilled Nursing News",
    queryLabel: "Skilled Nursing News site feed",
    kind: "rss",
    url: "https://skillednursingnews.com/feed/",
  },
  {
    id: "snn-medicare",
    folder: "context",
    title: "Skilled Nursing News - Medicare",
    queryLabel: "SNN category Medicare",
    kind: "rss",
    url: "https://skillednursingnews.com/category/medicare/feed/",
  },
  {
    id: "snn-medicaid",
    folder: "context",
    title: "Skilled Nursing News - Medicaid",
    queryLabel: "SNN category Medicaid",
    kind: "rss",
    url: "https://skillednursingnews.com/category/medicaid/feed/",
  },
  {
    id: "snn-compliance",
    folder: "context",
    title: "Skilled Nursing News - Compliance",
    queryLabel: "SNN category Compliance",
    kind: "rss",
    url: "https://skillednursingnews.com/category/compliance/feed/",
  },
  {
    id: "snn-legislation",
    folder: "context",
    title: "Skilled Nursing News - Legislation",
    queryLabel: "SNN category Legislation",
    kind: "rss",
    url: "https://skillednursingnews.com/category/legislation/feed/",
  },
  {
    id: "snn-staffing",
    folder: "context",
    title: "Skilled Nursing News - Staffing",
    queryLabel: "SNN category Staffing",
    kind: "rss",
    url: "https://skillednursingnews.com/category/staffing/feed/",
  },
  {
    id: "snn-ma",
    folder: "context",
    title: "Skilled Nursing News - Medicare Advantage",
    queryLabel: "SNN category Medicare Advantage",
    kind: "rss",
    url: "https://skillednursingnews.com/category/medicare-advantage/feed/",
  },
  {
    id: "snn-fraud",
    folder: "context",
    title: "Skilled Nursing News - Fraud",
    queryLabel: "SNN category Fraud",
    kind: "rss",
    url: "https://skillednursingnews.com/category/fraud/feed/",
  },
  {
    id: "snn-litigation",
    folder: "context",
    title: "Skilled Nursing News - Litigation",
    queryLabel: "SNN category Litigation",
    kind: "rss",
    url: "https://skillednursingnews.com/category/litigation/feed/",
  },
  {
    id: "willitcare",
    folder: "context",
    title: "Will It Care - national nursing-home changes",
    queryLabel: "Will It Care changes.xml",
    kind: "rss",
    url: "https://willitcare.com/changes.xml",
  },
  {
    id: "nhr-sff",
    folder: "context",
    title: "NursingHomeRating.org - Special Focus Facilities",
    queryLabel: "NursingHomeRating SFF XML",
    kind: "rss",
    url: "https://nursinghomerating.org/xml-sff.xml",
  },
  {
    id: "kff-medicaid",
    folder: "context",
    title: "KFF - Medicaid",
    queryLabel: "KFF Medicaid topic feed",
    kind: "rss",
    url: "https://www.kff.org/topic/medicaid/feed/",
  },
  {
    id: "kff-medicare",
    folder: "context",
    title: "KFF - Medicare",
    queryLabel: "KFF Medicare topic feed",
    kind: "rss",
    url: "https://www.kff.org/topic/medicare/feed/",
  },
  {
    id: "kff-private",
    folder: "context",
    title: "KFF - Private Insurance",
    queryLabel: "KFF private insurance topic feed",
    kind: "rss",
    url: "https://www.kff.org/topic/private-insurance/feed/",
  },
  {
    id: "kff-state",
    folder: "context",
    title: "KFF - State Health Policy Data",
    queryLabel: "KFF state health policy topic feed",
    kind: "rss",
    url: "https://www.kff.org/topic/state-health-policy-data/feed/",
  },
  {
    id: "aapacn-don",
    folder: "context",
    title: "AAPACN - LTC DON Chat",
    queryLabel: "AAPACN LTC DON Chat podcast",
    kind: "rss",
    url: "https://feeds.podcastmirror.com/ltc-don-chat",
  },
  {
    id: "aapacn-nac",
    folder: "context",
    title: "AAPACN - LTC NAC Chat",
    queryLabel: "AAPACN LTC NAC Chat podcast",
    kind: "rss",
    url: "https://feeds.podcastmirror.com/ltc-nac-chat",
  },
];
